name: tracker
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  smooth_page_indicator: 
  page_transition: 
  intl_phone_number_input: 
  pin_code_fields: ^7.4.0
  otp_autofill: 

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
 
  assets: 
    - asset/images/
    - asset/onboard/
